set -g @ukiyo-theme 'kanagawa/dragon'
run-shell "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
set -g window-active-style 'bg=#181616'   # dragonBlack2
set -g window-style       'bg=#1e1c1c'   # slightly lighter
