set -g window-active-style 'bg=#f2ecbc'   # lotusWhite3 — main bg
set -g window-style       'bg=#dcd7ba'   # lotusWhite0 — slightly
set -g @kanagawa-theme 'lotus'
run-shell "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
