set -g @ukiyo-theme 'kanagawa/lotus'
run-shell "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
set -g window-active-style 'bg=#f2ecbc'   # lotusWhite3 — main bg
set -g window-style       'bg=#c5c0ab'   # darker than lotusWhite0
