tap "homebrew/bundle"
tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "neovim"
brew "tmux"

# search/grep/diff
brew "fd"
brew "fzf"
brew "grep"
brew "psgrep"
brew "ripgrep"

# languages/tools
brew "gh"
brew "git-absorb"
brew "go"

# misc
brew "grip"
