tap "homebrew/bundle"
tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "neovim"
brew "tmux"
brew "mas"
brew "coreutils"

# search/grep/diff
brew "fd"
brew "fzf"
brew "grep"
brew "psgrep"
brew "ripgrep"
brew "gawk"

# tooling / source control
brew "gh"
brew "git-absorb"
brew "docker-credential-helper"
brew "gnupg"

# languages
brew "go"

# misc
brew "grip"
brew "topgrade"
brew "task"
